### ISSUE TITLE
What programming language used for the Higurashi based game ?

### ISSUE THREAD

**Issue by gagantous** [07th-mod/minagoroshi#10]
Out of curiosity, What programming language did the game used ? is it C ? or python ?

**Comment by ItaloKnox** [comment]
It's written in C# in framework created by Doddler in the Unity Engine.

Em qua, 21 de ago de 2019 22:07, Gagantous <notifications@github.com>
escreveu:

**Comment by ItaloKnox** [comment]
Since there was no follow up to the question, I will consider this issue answered.
