### ISSUE TITLE
Ooishis PS3 sprite blocks Akasakas sprite on first appearance

### ISSUE THREAD

**Issue by KBD20** [07th-mod/minagoroshi#11]
On first appearance after running Minagoroshi for a while (an hour or 2/from day 3) Akasakas sprite is blocked by Ooishis in the toy store, exiting and reloading the save seems to fix the issue.

Not sure if this is a bug with the mod or the base game - I'll try to reproduce it in the next few days.

**Comment by orian34** [comment]
pretty sure that's just the persistent sprite bug

**Comment by ghost** [comment]
Yes most likely.  https://github.com/07th-mod/higurashi-assembly/issues/45 . For minagoroshi I have an attempted fix for this.  Please ping me on discord if you'd like to try it.
It also is the kind of thing that is not reliably reproducible; if you experience this regularly, this is probably a different issue.  I'll close this for now, but feel free to reply or ping on discord if we need to investigate further.
