### ISSUE TITLE
Random comma on text/mina_katari21

### ISSUE THREAD

**Issue by FatesTimelines1337** [07th-mod/minagoroshi#13]
![mina_katari21](https://user-images.githubusercontent.com/38626341/71590381-394eac00-2af6-11ea-9ce6-04c856428ad5.png)
There's a random comma between the words last and call that I think should not be there.

**Comment by enumag** [comment]
Another minor typo here: ("mian" => "main" on the first line)

![mina_katari11](https://user-images.githubusercontent.com/539462/71779756-51707080-2fb9-11ea-9e75-b465c3ab3856.png)

**Comment by enumag** [comment]
Closed by #15
