### ISSUE TITLE
Question about the patch

### ISSUE THREAD

**Issue by mikem2567** [07th-mod/minagoroshi#21]
If I originally started minagoroshi without the patch am I able to download it and keep my save data?

**Comment by ItaloKnox** [comment]
You can technically keep your save data, but you should not load it. You
are going to run into multiple issues that will result in a softlock that
is irreversible. If you want to start from the point you where playing
before, you can use the chapter jump to get there. If you just want to keep
your save file for the future, the patch will not remove or modify it
(supposing you don't save over it).

Em seg, 29 de jun de 2020 15:21, mikem2567 <notifications@github.com>
escreveu:

**Comment by mikem2567** [comment]
Okay thank you for the reply, is chapter jump exclusive to the patch? I ask because I didn't notice an option to do that in the original

**Comment by ItaloKnox** [comment]
It's not, I think it's "buried" under the Extras menu. I also have a hard time remembering it without searching.
