### ISSUE TITLE
help me please...

### ISSUE THREAD

**Issue by saselsa** [07th-mod/minagoroshi#26]
Brother... I can only see the black screen when I run Minagorosi.
All the other chapters are fine.
I need your help. ᅲᅲ

**Comment by ItaloKnox** [comment]
Hi, please fill the support checklist, so we can help you: https://07th-mod.com/wiki/support-checklist/

Also, please do numbers 3 and 4 because the logs are super important and we can't help without them.

**Comment by drojf** [comment]
It's been nearly a year with no response so I'm closing this issue

The mod has an inbuilt help menu if you ever get the black screen bug which should help this kind of problem.
