### ISSUE TITLE
A voiceline sounds like it's said through the phone when it maybe shouldn't.

### ISSUE THREAD

**Issue by 0xC0FFEE-Mug** [07th-mod/minagoroshi#31]
The scene (`_mina_011_2`) takes place in the classroom, and for some reason Keiichi sounds like he's on the phone when he probably should just be speaking normally.

The line in question:
https://github.com/07th-mod/minagoroshi/blob/698c488ed11906809f2187585a13e9ae760725f4/Update/_mina_011_2.txt#L1299

~~I'm not familiar with the engine/assets, so I don't know if this is baked into the sound-file or post-processing applied by the engine.~~

**Comment by enumag** [comment]
There is no post processing for voices. It's in the audio file. Because of that it's most likely unfixable. There were some cases in question arcs where both normal and phonelike voice files were available for some scenes so it's worth checking out if the alternative exists but in answer arcs the chances are quite low.

**Comment by 0xC0FFEE-Mug** [comment]
disclaimer: I don't _really_ know how the naming scheme for voice files work so take what I say with a grain of salt, but I found the following.

The offending voicelines are `ps2/01/180100625` and `ps2/01/180100626`.
Most Keiichi voicelines in this file come from `ps3/s12/01/1801*.ogg`, `ps2/01/1801*.ogg`, `ps2/01/e_1801*.ogg`

I'm guessing the numbers are sequential. Looking in the `ps3/s12/01/` dir I see that it has a `180100624` and `180100627`, but neither `625`/`626`.

 I also `find`'ed for files with the same number in the entire `voice` dir but found nothing besides the originals.
```
$ find -name "**180100625**" -or -name "**180100626**"
./ps2/01/180100625.ogg
./ps2/01/180100626.ogg
```

Guess this can't be helped then like you said :-p.

**Comment by enumag** [comment]
The game only contains files that are actually used. For this it was necessary to check the full PS2 voice directory. And luckily the files do actually exist. I fixed it in https://github.com/07th-mod/minagoroshi/commit/468817a1356b816592e73d43e4a8c12bcd7fa070. Thanks for reporting!

**Comment by 0xC0FFEE-Mug** [comment]
Oh, awesome! Thanks a bunch!
