### ISSUE TITLE
Typo in _mina_027.txt

### ISSUE THREAD

**Issue by 0xC0FFEE-Mug** [07th-mod/minagoroshi#32]
Line in question: https://github.com/07th-mod/minagoroshi/blob/468817a1356b816592e73d43e4a8c12bcd7fa070/Update/_mina_027.txt#L439

My guess is that it should be `If it is them, shouldn't their name be on the van...?`

I'd make a commit/PR for this myself, but I don't know the development workflow for properly testing this ;-p

**Comment by orian34** [comment]
Fixed, thanks

**Comment by 0xC0FFEE-Mug** [comment]
Lovely, thanks for taking the time to check it out!
