### ISSUE TITLE
Missing things

### ISSUE THREAD

**Issue by andOlga** [07th-mod/minagoroshi#7]
This issue is created to track the stuff that exists in the base game, in the PS3 version, in older releases of our mod etc, but is missing in the current Minagoroshi mod.

- [x] Missing controls screen at the start of the game
- [x] Missing buttons for the Extras screen (Staff Room, Chapter Jump, Tips). The standard blue ones are displayed.
- [x] Hanyuu has the nametag colour of a generic NPC.
- [x] PS2 volumes are much quieter than PS3 ones. (540 would be good for PS2 voices according to Orian)
- [x] The [fake choice](https://youtu.be/hfHKH4itBeU?t=5163) towards the end of the chapter is completely ruined by MG and is replaced with just regular text. Should be possible to implement using images.
- [x] Fix compiler missing files detection - doesn't recognise `DrawBustshotWithFiltering`
- [x] Fix TipsPrefab
- [x] Use better translation for Katari images
- [x] Use better font for Takano's rant
- [ ] Remove `DisplayWindow` calls after `DrawBustshot` in ADV compilation
- [x] Fix Keiichi swapping in and out from phone distortion around [this part](https://github.com/07th-mod/minagoroshi/blob/d2c4192343c078f409b8883d4fd3c95cb834200f/Update/_mina_011_2.txt#L1405). He is present so there should be no distortion.
- [x] Add tips.json
- [x] Try using `ModSetLayerFilter` https://github.com/07th-mod/higurashi-assembly/issues/38
- [ ] Try fixing the remaining known issues

**Comment by Naegles** [comment]
Do you think it is possible to emulate how the ps3 version did the fake choice? 
I really like how they did that.
Maybe it's possible to just insert a short video?
Depends on how long the video load times are I suppose.

**Comment by enumag** [comment]
@Naegles Posting the YT link from Discord: https://www.youtube.com/watch?v=hfHKH4itBeU&feature=youtu.be&t=5163

I think we can do this with a couple of images and swapping them without the user's interaction. What do you think @orian34?

**Comment by enumag** [comment]
Volume: @orian34 said a good volume for PS2 voices would be aroung 540.

**Comment by enumag** [comment]
- [ ] Fix compiler missing files detection - doesn't recognice `DrawBustshotWithFiltering`
- [ ] Fix TipsPrefab
- [ ] Use better translation for Katari images
- [ ] Use better font for Takano's rant
