### ISSUE TITLE
TIPS room missing from Extras menu

### ISSUE THREAD

**Issue by phantomyeet** [07th-mod/minagoroshi#8]
[higurashi07.zip](https://github.com/07th-mod/minagoroshi/files/3517064/higurashi07.zip)

**Comment by enumag** [comment]
Apparently tips are not unlocked correctly. See [this image](https://cdn.discordapp.com/attachments/392489108875771906/613067504780312582/unknown.png). Staff room is already unlocked which means the game was finished. Still the tips screen is not available.

This happened to phantom when using the 1.0.0 graphics patch. His save files are in the first comment.

Strange thing is that it did not happen to orian when he was updating the game.

**Comment by ghost** [comment]
Confirmed the issue with another user.

@orian34 did you ever check this menu prior to finishing the game?  Did you change anything relevant in the scripts for development purposes, like set flags like GHighestChapter or GMinagoroshiDay or the one that's something like GGameClear?
